### PR TITLE
[HaxeProject][AdditionalCompilerOptions] Added support for hxml files. fixes #1793. part2

### LINKED ISSUE #1793: [Haxe] References libs not found
I used to be able to add -lib in "Additional Dependencies", or include other .hxml there that might have -lib as well. With latest HaxeDevelop 5.3 the libraries are only listed if they are part of the "Libraries" configuration section, which is a regression vs 5.2

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by SlavaRa** [comment]
@ncannasse you can try this https://ci.appveyor.com/project/FlashDevelop/flashdevelop-devel/build/5.3.1.36-huokctkt/artifacts and write that everything is fine if I solved your problem

File: External/Plugins/ProjectManager/Projects/Haxe/HaxeProject.cs [hunk 1]
```diff
@@ -299,13 +300,34 @@ public static HaxeProject Load(string path)
...
+                    var adds = new HashSet<string>(options.Additional.Where(line => !line.TrimEnd().EndsWith(".hxml")));
+                    var target = string.Empty;
+                    var haxeTarget = string.Empty;
+                    var output = string.Empty;
+                    var mainClass = string.Empty;
+                    project.ParseHxmlEntries(hxmls, defs, cps, libs, adds, ref target, ref haxeTarget, ref output, ref mainClass);
+                    if (libs.Count > 0) options.Libraries = libs.ToArray();
+                    if (defs.Count > 0) options.Directives = defs.ToArray();
+                    if (adds.Count > 0) options.Additional = adds.ToArray();
+                    if (cps.Count > 0)
```
Comment (elsassph) [inline External/Plugins/ProjectManager/Projects/Haxe/HaxeProject.cs]: Maybe only if the number of cps has changed?

File: External/Plugins/ProjectManager/Projects/Haxe/HaxeProject.cs [hunk 2]
```diff
@@ -436,11 +458,39 @@ private void ParseHxmlEntries(string[] lines, List<string> defs, List<string> cp
...
+                            {
+                                case "cp":
+                                case "resource":
+                                case "lib-java":
+                                case "lib-net":
+                                case "lib-std":
+                                case "swf-lib":
+                                case "swf-lib-extern":
+                                case "cmd":
+                                    var path = match.Groups[2].Value.Trim();
```
Comment (elsassph) [inline External/Plugins/ProjectManager/Projects/Haxe/HaxeProject.cs:486]: Does it handle quoted paths?

File: External/Plugins/ProjectManager/Projects/Haxe/HaxeProject.cs [hunk 3]
```diff
@@ -385,7 +407,7 @@ private void ParseHXML(string[] raw)
             }
         }
 
-        private void ParseHxmlEntries(string[] lines, List<string> defs, List<string> cps, List<string> libs, List<string> add, ref string target, ref string haxeTarget, ref string output)
+        private void ParseHxmlEntries(IEnumerable<string> lines, ICollection<string> defs, ICollection<string> cps, ICollection<string> libs, ICollection<string> add, ref string target, ref string haxeTarget, ref string output, ref string mainClass)
```
Comment (elsassph) [inline External/Plugins/ProjectManager/Projects/Haxe/HaxeProject.cs]: Good candidate for unit tests

File: External/Plugins/ProjectManager/Projects/Haxe/HaxeProject.cs [hunk 4]
```diff
@@ -436,11 +458,39 @@ private void ParseHxmlEntries(string[] lines, List<string> defs, List<string> cp
                 }
                 else if (!trimmedLine.StartsWith("#") && trimmedLine.EndsWith(".hxml", StringComparison.OrdinalIgnoreCase))
                 {
-                    string subhxml = this.GetAbsolutePath(trimmedLine);
-                    if (File.Exists(subhxml))
+                    var subhxml = GetAbsolutePath(trimmedLine);
```
Comment (elsassph) [inline External/Plugins/ProjectManager/Projects/Haxe/HaxeProject.cs]: In case of recursive hxmls in different sub folders, should the function be provided a reference path?

**Comment by SlavaRa** [comment]
I'll think over all the comments in a couple of weeks.
