### PR TITLE
RenameFile: Fix renaming that involves only a case change

### LINKED ISSUE #1288: Renaming class: avoid replace existing file warning if only case is changed (on Windows).
Got a project with interface files called `iSomeInterface`. Renaming it to `ISomeInterface` and getting a confirm dialog that file already exists (since on Windows file system is case-insensitive), "Would you like to replace?". Basically, on Windows, this dialog should only appear if `oldName.toLowerCase() != newName.toLowerCase`. Considering FD would (hopefully) be available for Linux one day, this should only apply on a case-insensitive filesystem.

### PR DESCRIPTION
**Pull request by gene-pavlovsky**
Fixes #1288 and #2194 

One stone, two rabbits. Hopefully got both :)

### CODE REVIEW

File: External/Plugins/CodeRefactor/Commands/RenameFile.cs [hunk 1]
```diff
@@ -44,19 +44,20 @@ protected override void ExecutionImplementation()
...
+                filePath += "$renaming$";
+                File.Move(oldPath, filePath);
             }
             if (!Path.IsPathRooted(newPath)) newPath = Path.Combine(Path.GetDirectoryName(oldPath), newPath);
 
             if (FileHelper.ConfirmOverwrite(newPath))
             {
-                FileHelper.ForceMove(oldPath, newPath);
+                FileHelper.ForceMove(filePath, newPath);
                 DocumentManager.MoveDocuments(oldPath, newPath);
```
Comment (gene-pavlovsky) [inline External/Plugins/CodeRefactor/Commands/RenameFile.cs]: The issue here was that `oldPath` contained `$renaming$`, so document manager couldn't find any matching documents, and the commit message generated by the source control dialog contained this unwanted `$renaming$`

**Comment by gene-pavlovsky** [comment]
Covered the other cases.
I hope somebody could explain to me a scenario where a `Move` command might involve a rename that involves only a case change. I couldn't reproduce any of the 4 `$renaming$` cases in `Move` during my testing.
