### PR TITLE
Fix exception caused by interpolation completion in comments, closes #772

### LINKED ISSUE #772: [haxe] FD tries to show up completion for string interpolation in docs, errors.
Say, if you have some
```haxe
/// '
static function main() { }
```
the moment you insert a "$" after that single quote, you get this exception:
```
Object reference not set to an instance of an object.

   at ASCompletion.Completion.ASComplete.HandleInterpolationCompletion(ScintillaControl sci, Boolean autoHide, Boolean expressions)
   at ASCompletion.Completion.ASComplete.OnChar(ScintillaControl Sci, Int32 Value, Boolean autoHide)
```

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

File: External/Plugins/ASCompletion/Completion/ASComplete.cs [hunk 1]
```diff
@@ -88,8 +88,12 @@ static public bool OnChar(ScintillaControl Sci, int Value, bool autoHide)
                 char prevValue = (char)Sci.CharAt(position - 2);
                 bool skipQuoteCheck = false;
 
+                Sci.Colourise(0, -1);
+                int stylemask = (1 << Sci.StyleBits) - 1;
```
Comment (elsassph) [inline External/Plugins/ASCompletion/Completion/ASComplete.cs]: Sci.BaseStyleAt() applies the mask.

Comment (Gama11) [inline External/Plugins/ASCompletion/Completion/ASComplete.cs]: Updated.
