### PR TITLE
Extended Shortcut Backward Compatibility

### LINKED ISSUE #1303: Advanced Shortcut - breaks plugin(s)
Originally reported in [here](https://github.com/fdorg/flashdevelop/pull/1245#issuecomment-242407347)
On FD startup, there are around 10 identical exceptions:

```
Method not found: 'Boolean ASCompletion.Completion.ASComplete.OnShortcut(System.Windows.Forms.Keys, ScintillaNet.ScintillaControl)'.

   at PostfixCodeCompletion.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
   at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```

This is the plugin throwing the exceptions: https://github.com/SlavaRa/fdplugin-postfix-code-completion

### PR DESCRIPTION
**Pull request by wise0704**
Closes #1303 
Sorry @Neverbirth :P

### CODE REVIEW

File: External/Plugins/ProjectManager/Controls/FDMenus.cs [hunk 1]
```diff
@@ -182,16 +182,16 @@ public void ToggleDebugRelease()
...
+        public ToolStripMenuItem NewProject;
+        public ToolStripMenuItem OpenProject;
+        public ToolStripMenuItem ImportProject;
+        public ToolStripMenuItem CloseProject;
+        public ToolStripMenuItem OpenResource;
+        public ToolStripMenuItem TestMovie;
+        public ToolStripMenuItem RunProject;
+        public ToolStripMenuItem BuildProject;
+        public ToolStripMenuItem CleanProject;
+        public ToolStripMenuItem Properties;
```
Comment (wise0704) [inline External/Plugins/ProjectManager/Controls/FDMenus.cs]: This type of rollback should be reverted for the next major update, when the compatibility is not needed.
Since the `ToolStripMenuItexEx.ShortcutKeys` is not an overridden member, every time you need to use `ShortcutKeys` on these, you need to cast them to `ToolStripMenuItemEx`.

File: External/Plugins/ProjectManager/Controls/FDMenus.cs [hunk 2]
```diff
@@ -218,13 +218,13 @@ public ProjectMenu()
 
             OpenResource = new ToolStripMenuItemEx(TextHelper.GetString("Label.OpenResource"));
             OpenResource.Image = PluginBase.MainForm.FindImage("209");
-            OpenResource.ShortcutKeys = Keys.Control | Keys.R;
+            ((ToolStripMenuItemEx) OpenResource).ShortcutKeys = Keys.Control | Keys.R;
```
Comment (wise0704) [inline External/Plugins/ProjectManager/Controls/FDMenus.cs]: Like this.

**Comment by wise0704** [comment]
These are all the public signature changes that I missed in the last PR.
