### PR TITLE
[ASComplete] Fixed show calltip if previous argument uses array comprehensions. fixes #764

### LINKED ISSUE #764: [Haxe] Calltip completion breaks if previous argument uses array comprehension
``` haxe
class Main {
    static function main() {
        test([for (i in 0...10) i]
    }

    static function test(a:Array<Int>, b:Int) {

    }
}
```

Expected behavior: the calltip completion pops up after typing the comma like here:

Actual: nothing happens.

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by Neverbirth** [comment]
I will try to check this one today.

File: External/Plugins/ASCompletion/Completion/ASComplete.cs [hunk 1]
```diff
@@ -1782,66 +1782,38 @@ private static ClassModel ResolveParameterType(int paramIndex, bool indexTypeOnl
...
         {
             int parCount = 0;
             int braCount = 0;
             int comaCount = 0;
             int arrCount = 0;
-            var genCount = 0;
-            var dquCount = 0;
-            var squCount = 0;
+            var genCount = 0;
+            sci.Colourise(0, -1);
```
Comment (Neverbirth) [inline External/Plugins/ASCompletion/Completion/ASComplete.cs]: My understanding is that calling `Colourise(0, -1)` is expensive, and some of the functions calling `FindParameterIndex` are already calling this before (although it's not easy to find some of them by just browsing the code). @elsassph @Meychi is my comment right or am I remembering wrong/something else? If so then I guess it would be better to identify which functions calling this are not calling `Colourise` before?

Other than this I think it's ok.

Comment (elsassph) [reply External/Plugins/ASCompletion/Completion/ASComplete.cs]: We could add some logging of calls to `Colourise` to check if we're abusing it yes.

**Comment by SlavaRa** [comment]
is it okay or should I close this request?

**Comment by SlavaRa** [comment]
ok, if not necessary, I will close after release :)

**Comment by Neverbirth** [comment]
I missed your message. The PR is ok, but that sci.Colourise call should be checked, on the cases I checked it is not necessary because it is already called before, so making an extra call is wasting CPU from our understanding because it makes scintilla to reparse and recolourose everything. But I didn't check for every case where `FindParameterIndex` is called.

**Comment by SlavaRa** [comment]
how can I verify that it was called up before?

**Comment by Neverbirth** [comment]
I'm not sure if there is a built-in way. Although if my understanding is correctly we can implement it in scintillacontrol.

I would say the best is to assume inside FindParameterIndex has always been called, and make sure that it is always the case.

@elsassph am I correct? 

We could ask in the scintilla group. We should update our scintilla...

**Comment by SlavaRa** [comment]
Well, I'll be waiting for a solution, but in the future, I think I can release my version of the plug-ins so that some users get the functionality while you make the decision))

**Comment by Neverbirth** [comment]
Merged! Thanks. Note I will make slight modifications regarding the Colourise call.
