### PR TITLE
 [Haxe][CodeGenerator] Fixed autoimport if current class is Enum or Typedef. fixes #1833

### LINKED ISSUE #1833: Contextual import generation doesn't work in Haxe enums
Create a new enum file, give one of the constructors an argument of a type which should be imported.
Press `Ctrl+Shift+1` with the cursor on the argument type.
Result: No contextual code generation available.
Expected: Auto-import the type.

```haxe
package;

enum TimerSignal {
  Fire(timer:Timer); // try to import Timer
}
```

### PR DESCRIPTION
**Pull request by SlavaRa**
fixes #1833

### CODE REVIEW

**Comment by SlavaRa** [comment]
@Neverbirth ?

File: External/Plugins/HaXeContext/Completion/CodeGenerator.cs [hunk 1]
```diff
@@ -10,13 +10,18 @@
 
 namespace HaXeContext.Completion
 {
-    internal class CodeGenerator : IContextualGenerator
+    internal class CodeGenerator : ASGenerator
     {
-        public bool ContextualGenerator(ScintillaControl sci, List<ICompletionListItem> options, ASResult expr)
+        public override bool ContextualGenerator(ScintillaControl sci, List<ICompletionListItem> options, ASResult expr)
         {
-            if ((ASContext.Context.CurrentClass.Flags & FlagType.Interface) != 0
```
Comment (elsassph) [inline External/Plugins/HaXeContext/Completion/CodeGenerator.cs]: Interface handling isn't needed anymore?

Comment (SlavaRa) [reply External/Plugins/HaXeContext/Completion/CodeGenerator.cs]: Thanks, fixed. I will write test for it today.
