### PR TITLE
Closing brace inside strings should not unindent

### LINKED ISSUE #489: Typing } in a string eats a tab
Seems to happen in 4.6.4 as well, so it's not a recent regression (if it is one).

### PR DESCRIPTION
**Pull request by wise0704**
Closes #489

Doesn't solve the second issue in the comments of the referenced issue.

### CODE REVIEW

File: PluginCore/ScintillaNet/ScintillaControl.cs [hunk 1]
```diff
@@ -5902,14 +5903,11 @@ private void OnSmartIndent(ScintillaControl ctrl, int ch)
...
-                            int previousIndent = GetLineIndentation(curLine - 1);
-                            int match = SafeBraceMatch(position - 1);
-                            if (match != -1)
+                            int position = CurrentPos - 1;
+                            int match = SafeBraceMatch(position); //SafeBraceMatch() calls Colourise(0, -1)
+                            if (match != -1 && !PositionIsInString(position))
                             {
-                                previousIndent = GetLineIndentation(LineFromPosition(match));
-                                IndentLine(curLine, previousIndent);
+                                IndentLine(LineFromPosition(position), GetLineIndentation(LineFromPosition(match)));
```
Comment (Neverbirth) [inline PluginCore/ScintillaNet/ScintillaControl.cs]: You are now doing `CurrentPos - 1`, so the line to indent may be the previous one.

Comment (wise0704) [inline PluginCore/ScintillaNet/ScintillaControl.cs]: `CurrentPos - 1` is always the index of `}`, which should be the same line as `CurrentPos`

Comment (Neverbirth) [inline PluginCore/ScintillaNet/ScintillaControl.cs]: Right
